### ISSUE TITLE
Example LoRaWAN_Class_A does not find E5 board

### ISSUE THREAD

**Issue by SensorsIot** [SylvainMontagny/LoRaE5#3]
Hi Sylvain,

I tried to use your new library with an XIAO-S3 board. Unfortunately, it does not work. It seems that the UART definitions do not match. I will investigate to find it out, but I suggest that the connection details are described in the readme.
In addition, my colleague Kurt showed me that the serial definitions are in a .h file in the library folder. I think that is not a good place. Such definitions (including the pins for the ESP32) should be in the sketch itself because your library will be used for several MCUs and boards.

Another suggestion: There are a few other similar boards available like the RA-08h from AI-Thinker or the E78 from ebyte. Are there plans that your library will support these boards, too?

**Comment by SylvainMontagny** [comment]
Hi SensorsIoT,
Can you confirm the lib version you are working with ? v2 ? Just to be sure.
We will check it out. As for the Board supported, we previously planned to build this lib only for our Leonardo and Arduino zero... so indeed UART definitions are probably wrong.

**Comment by SensorsIot** [comment]
Yes, I use V2. And I found the issue: 

I had to change the second line of the setup() in the library:
void LORAE5::setup(uint8_t region, bool mode, uint8_t devClass, uint8_t sf, bool adr, bool confirmed, uint8_t portUp, bool SEND_BY_PUSH_BUTTON, uint32_t FRAME_DELAY){
  unsigned long startTime = millis();
  LoRa_Serial.begin(9600, SERIAL_8N1, D7, D6);

If you would add the two pins in the setup definition, the library would be more universally usable. I for example will use it with an ATTINY because I do not need a lot of power to read two switches (most of the work is done inside the chip)

**Comment by SylvainMontagny** [comment]
That's what we will do. Thanks
