### ISSUE TITLE
Test board success

### ISSUE THREAD

**Issue by aemmenet** [SylvainMontagny/LoRaE5#5]
I tested the Library V3.0.0 on my DIY (do-it-yorself) "polylab" Development-Board with a Microchip AVR DD-series MCU (AVR64DD32) and the additional Board Manager "DxCore" for Arduino support installed in the Arduino IDE.

https://github.com/aemmenet/polylab
https://www.microchip.com/en-us/product/avr64dd32
https://github.com/SpenceKonde/DxCore

The LoRaWAN Class A example sketch with a I2C Bosch BME280-Sensor added and switching the Arduino LED_BUILTIN on the Dev. Board according to the PayloadDown value works perfect.

https://github.com/aemmenet/polylab/blob/master/Software/LoRaWAN_Class_A.ino

My DIY "polylab" Development-Board has a mikroBUS socket. The Seeed-Studio Wio-E5 LoRa Module sits on a DIY mikroBUS board compatible with the Grove Wio E5 LoRa-E5 Network Module.

https://github.com/aemmenet/polylab/#mikroBUS_LoRa-E5

As my Serial-Connections are different and there is no Arduino platform/board macro for my DIY Dev. Board i needed to cross the Serial-Configuration in the config_board.h file manually. It's great that this hardware-configuration no longer has to be done in the library.

#define Debug_Serial      Serial1
#define LoRa_Serial       Serial

**Comment by SylvainMontagny** [comment]
Nice, thanks for the feedback
